version: "3"

services:
  ocr:
    build:
      context: .
      dockerfile: Dockerfile
    image: ocr
    container_name: ocr
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "your_value"
      PROJECT_ID: "your_value"
      LOCATION_ID: "your_value"
      PROCESSOR_ID: "your_value"
      MODEL_VERSION: "your_value"
      API_KEY: "your_value"
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - ocr-network
    command: gunicorn app:app -w 4 -t 90 --log-level=debug -b 0.0.0.0:8000 --reload --threads 2 --worker-class gevent --keep-alive 5 --timeout 60 --worker-connections 1000
networks:
  ocr-network:
    driver: bridge
